properties = {
    "align-content": "stretch",
    "align-items": "stretch",
    "align-self": "auto",
    "all": "initial",
    "animation": "none 0s ease 0s 1 normal none running",
    "animation-delay": "0s",
    "animation-direction": "normal",
    "animation-duration": "0s",
    "animation-fill-mode": "none",
    "animation-iteration-count": "1",
    "animation-name": "none",
    "animation-play-state": "running",
    "animation-timing-function": "ease",
    "backdrop-filter": "none",
    "backface-visibility": "visible",
    "background": "0% 0% / auto repeat scroll padding-box border-box #000000",
    "background-attachment": "scroll",
    "background-blend-mode": "normal",
    "background-clip": "border-box",
    "background-color": "transparent",
    "background-image": "none",
    "background-origin": "padding-box",
    "background-position": "0% 0%",
    "background-repeat": "repeat",
    "background-size": "auto auto",
    "block-size": "auto",
    "border": "0px none rgb(0, 0, 0)",
    "border-block": "0px none rgb(0, 0, 0)",
    "border-block-color": "currentcolor",
    "border-block-end": "0px none rgb(0, 0, 0)",
    "border-block-end-color": "currentcolor",
    "border-block-end-style": "none",
    "border-block-end-width": "medium",
    "border-block-start": "0px none rgb(0, 0, 0)",
    "border-block-start-color": "currentcolor",
    "border-block-start-style": "none",
    "border-block-start-width": "medium",
    "border-block-style": "none",
    "border-block-width": "medium",
    "border-bottom": "0px none rgb(0, 0, 0)",
    "border-bottom-color": "currentcolor",
    "border-bottom-left-radius": "0px",
    "border-bottom-right-radius": "0px",
    "border-bottom-style": "none",
    "border-bottom-width": "medium",
    "border-collapse": "separate",
    "border-color": "rgb(0, 0, 0)",
    "border-end-end-radius": "0px",
    "border-end-start-radius": "0px",
    "border-image": "none",
    "border-image-outset": "0",
    "border-image-repeat": "stretch",
    "border-image-slice": "100%",
    "border-image-source": "none",
    "border-image-width": "1",
    "border-inline": "0px none rgb(0, 0, 0)",
    "border-inline-color": "currentcolor",
    "border-inline-end": "0px none rgb(0, 0, 0)",
    "border-inline-end-color": "currentcolor",
    "border-inline-end-style": "none",
    "border-inline-end-width": "medium",
    "border-inline-start": "0px none rgb(0, 0, 0)",
    "border-inline-start-color": "currentcolor",
    "border-inline-start-style": "none",
    "border-inline-start-width": "medium",
    "border-inline-style": "none",
    "border-inline-width": "medium",
    "border-left": "0px none rgb(0, 0, 0)",
    "border-left-color": "currentcolor",
    "border-left-style": "none",
    "border-left-width": "medium",
    "border-radius": "0px",
    "border-right": "0px none rgb(0, 0, 0)",
    "border-right-color": "currentcolor",
    "border-right-style": "none",
    "border-right-width": "medium",
    "border-spacing": "0px 0px",
    "border-start-end-radius": "0px",
    "border-start-start-radius": "0px",
    "border-style": "none",
    "border-top": "0px none rgb(0, 0, 0)",
    "border-top-color": "currentcolor",
    "border-top-left-radius": "0px",
    "border-top-right-radius": "0px",
    "border-top-style": "none",
    "border-top-width": "medium",
    "border-width": "medium",
    "bottom": "auto",
    "box-decoration-break": "slice",
    "box-shadow": "none",
    "box-sizing": "content-box",
    "break-after": "auto",
    "break-before": "auto",
    "break-inside": "auto",
    "caption-side": "top",
    "caret-color": "auto",
    "clear": "none",
    "clip": "auto",
    "clip-path": "none",
    "color": "rgb(0, 0, 0)",
    "column-count": "auto",
    "column-fill": "balance",
    "column-gap": "normal",
    "column-rule": "0px none rgb(0, 0, 0)",
    "column-rule-color": "currentcolor",
    "column-rule-style": "none",
    "column-rule-width": "medium",
    "column-span": "none",
    "column-width": "auto",
    "columns": "auto auto",
    "content": "normal",
    "continue": "auto",
    "counter-increment": "none",
    "counter-reset": "none",
    "counter-set": "none",
    "cursor": "auto",
    "direction": "ltr",
    "display": "inline",
    "empty-cells": "show",
    "filter": "none",
    "flex": "0 1 auto",
    "flex-basis": "auto",
    "flex-direction": "row",
    "flex-flow": "row nowrap",
    "flex-grow": "0",
    "flex-shrink": "1",
    "flex-wrap": "nowrap",
    "float": "none",
    "font": "normal normal normal medium/normal sans-serif",
    "font-family": "sans-serif",
    "font-feature-settings": "normal",
    "font-kerning": "auto",
    "font-language-override": "normal",
    "font-optical-sizing": "auto",
    "font-size": "medium",
    "font-size-adjust": "none",
    "font-stretch": "normal",
    "font-style": "normal",
    "font-synthesis": "weight style",
    "font-variant": "normal",
    "font-variant-caps": "normal",
    "font-variant-east-asian": "normal",
    "font-variant-ligatures": "normal",
    "font-variant-numeric": "normal",
    "font-variant-position": "normal",
    "font-variation-settings": "normal",
    "font-weight": "medium",
    "gap": "normal normal",
    "grid": "none / none / none / row / auto / auto",
    "grid-area": "auto / auto / auto / auto",
    "grid-auto-columns": "auto",
    "grid-auto-flow": "row",
    "grid-auto-rows": "auto",
    "grid-column": "auto / auto",
    "grid-column-end": "auto",
    "grid-column-gap": "normal",
    "grid-column-start": "auto",
    "grid-gap": "normal normal",
    "grid-row": "auto / auto",
    "grid-row-end": "auto",
    "grid-row-gap": "normal",
    "grid-row-start": "auto",
    "grid-template": "none / none / none",
    "grid-template-areas": "none",
    "grid-template-columns": "none",
    "grid-template-rows": "none",
    "hanging-punctuation": "none",
    "height": "auto",
    "hyphens": "manual",
    "image-orientation": "auto",
    "image-rendering": "auto",
    "image-resolution": "normal",
    "inline-size": "auto",
    "inset": "auto auto auto auto",
    "inset-block": "auto auto",
    "inset-block-end": "auto",
    "inset-block-start": "auto",
    "inset-inline": "auto auto",
    "inset-inline-end": "auto",
    "inset-inline-start": "auto",
    "isolation": "auto",
    "justify-content": "normal",
    "justify-items": "legacy",
    "justify-self": "auto",
    "left": "auto",
    "letter-spacing": "normal",
    "line-break": "auto",
    "line-height": "normal",
    "list-style": "disc outside none",
    "list-style-image": "none",
    "list-style-position": "outside",
    "list-style-type": "disc",
    "margin": "0px",
    "margin-block": "0px",
    "margin-block-end": "0px",
    "margin-block-start": "0px",
    "margin-bottom": "0px",
    "margin-inline": "0px",
    "margin-inline-end": "0px",
    "margin-inline-start": "0px",
    "margin-left": "0px",
    "margin-right": "0px",
    "margin-top": "0px",
    "margin-right": "0px",
    "margin-bottom": "0px",
    "margin-left": "0px",
    "mask": "none",
    "mask-border": "none",
    "mask-border-mode": "alpha",
    "mask-border-outset": "0px",
    "mask-border-repeat": "stretch",
    "mask-border-slice": "0 fill",
    "mask-border-source": "none",
    "mask-border-width": "auto",
    "mask-clip": "border-box",
    "mask-composite": "source-over",
    "mask-image": "none",
    "mask-mode": "match-source",
    "mask-origin": "border-box",
    "mask-position": "center",
    "mask-repeat": "no-repeat",
    "mask-size": "auto",
    "mask-type": "luminance",
    "max-block-size": "none",
    "max-height": "none",
    "max-inline-size": "none",
    "max-width": "none",
    "min-block-size": "0px",
    "min-height": "auto",
    "min-inline-size": "0px",
    "min-width": "auto",
    "mix-blend-mode": "normal",
    "object-fit": "fill",
    "object-position": "50% 50%",
    "offset": "none 0px auto auto",
    "offset-anchor": "auto",
    "offset-distance": "0px",
    "offset-path": "none",
    "offset-position": "auto",
    "offset-rotate": "auto",
    "opacity": "1",
    "order": "0",
    "orphans": "2",
    "outline": "rgb(0, 0, 0) none 0px",
    "outline-color": "rgb(0, 0, 0)",
    "outline-offset": "0px",
    "outline-style": "none",
    "outline-width": "medium",
    "overflow": "visible",
    "overflow-anchor": "auto",
    "overflow-block": "visible",
    "overflow-clip-margin": "auto",
    "overflow-inline": "visible",
    "overflow-wrap": "normal",
    "overflow-x": "visible",
    "overflow-y": "visible",
    "overscroll-behavior": "auto auto",
    "overscroll-behavior-block": "auto",
    "overscroll-behavior-inline": "auto",
    "overscroll-behavior-x": "auto",
    "overscroll-behavior-y": "auto",
    "padding": "0px",
    "padding-block": "0px",
    "padding-block-end": "0px",
    "padding-block-start": "0px",
    "padding-bottom": "0px",
    "padding-inline": "0px",
    "padding-inline-end": "0px",
    "padding-inline-start": "0px",
    "padding-left": "0px",
    "padding-right": "0px",
    "padding-top": "0px",
    "page-break-after": "auto",
    "page-break-before": "auto",
    "page-break-inside": "auto",
    "paint-order": "fill stroke markers",
    "perspective": "none",
    "perspective-origin": "50% 50%",
    "place-content": "normal normal",
    "place-items": "normal normal",
    "place-self": "auto auto",
    "pointer-events": "auto",
    "position": "static",
    "quotes": "auto",
    "resize": "none",
    "right": "auto",
    "rotate": "0deg",
    "row-gap": "normal",
    "ruby-align": "space-around",
    "ruby-merge": "separate",
    "ruby-position": "over",
    "scale": "1 1",
    "scroll-behavior": "auto",
    "scroll-margin": "0px",
    "scroll-margin-block": "0px",
    "scroll-margin-block-end": "0px",
    "scroll-margin-block-start": "0px",
    "scroll-margin-bottom": "0px",
    "scroll-margin-inline": "0px",
    "scroll-margin-inline-end": "0px",
    "scroll-margin-inline-start": "0px",
    "scroll-margin-left": "0px",
    "scroll-margin-right": "0px",
    "scroll-margin-top": "0px",
    "scroll-padding": "auto",
    "scroll-padding-block": "auto",
    "scroll-padding-block-end": "auto",
    "scroll-padding-block-start": "auto",
    "scroll-padding-bottom": "auto",
    "scroll-padding-inline": "auto",
    "scroll-padding-inline-end": "auto",
    "scroll-padding-inline-start": "auto",
    "scroll-padding-left": "auto",
    "scroll-padding-right": "auto",
    "scroll-padding-top": "auto",
    "scroll-snap-align": "none",
    "scroll-snap-stop": "normal normal",
    "scroll-snap-type": "none",
    "scrollbar-color": "auto",
    "scrollbar-gutter": "auto",
    "scrollbar-width": "auto",
    "shape-image-threshold": "0",
    "shape-margin": "0px",
    "shape-outside": "none",
    "tab-size": "8",
    "table-layout": "auto",
    "text-align": "start",
    "text-align-last": "auto",
    "text-combine-upright": "none",
    "text-decoration": "none solid rgb(0, 0, 0)",
    "text-decoration-color": "rgb(0, 0, 0)",
    "text-decoration-line": "none",
    "text-decoration-skip": "objects",
    "text-decoration-style": "solid",
    "text-decoration-thickness": "auto",
    "text-emphasis": "none",
    "text-emphasis-color": "currentcolor",
    "text-emphasis-position": "over right",
    "text-emphasis-style": "none",
    "text-indent": "0px",
    "text-justify": "auto",
    "text-orientation": "mixed",
    "text-overflow": "clip",
    "text-rendering": "auto",
    "text-shadow": "none",
    "text-transform": "none",
    "text-underline-offset": "auto",
    "text-underline-position": "auto",
    "top": "auto",
    "transform": "none",
    "transform-box": "view-box",
    "transform-origin": "50% 50% 0px",
    "transform-style": "flat",
    "transition": "all 0s ease 0s",
    "transition-delay": "0s",
    "transition-duration": "0s",
    "transition-property": "all",
    "transition-timing-function": "ease",
    "translate": "0px 0px",
    "unicode-bidi": "normal",
    "user-select": "auto",
    "vertical-align": "baseline",
    "visibility": "visible",
    "white-space": "normal",
    "widows": "2",
    "width": "auto",
    "will-change": "auto",
    "word-break": "normal",
    "word-spacing": "normal",
    "word-wrap": "normal",
    "writing-mode": "horizontal-tb",
    "z-index": "auto"
}
